package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"PostService/internal/domain"
	"context"
	"fmt"

	"github.com/vektah/gqlparser/v2/gqlerror"
)

// Post is the resolver for the post field.
func (r *commentResolver) Post(ctx context.Context, obj *domain.Comment) (int, error) {
	panic(fmt.Errorf("not implemented: Post - post"))
}

// ReplyTo is the resolver for the replyTo field.
func (r *commentResolver) ReplyTo(ctx context.Context, obj *domain.Comment) (*int, error) {
	panic(fmt.Errorf("not implemented: ReplyTo - replyTo"))
}

// Replies is the resolver for the replies field.
func (r *commentResolver) Replies(ctx context.Context, obj *domain.Comment) ([]*domain.Comment, error) {
	replies, err := r.CommentService.GetReplies(obj.ID)
	if err != nil {
		return nil, &gqlerror.Error{Message: err.Error()}
	}
	result := make([]*domain.Comment, len(replies))
	for i := range replies {
		c := replies[i]
		result[i] = &c
	}
	return result, nil
}

// CreatePost is the resolver for the createPost field.
func (r *mutationResolver) CreatePost(ctx context.Context, input domain.CreatePostInput) (*domain.Post, error) {
	post, err := r.PostService.CreatePost(input)
	if err != nil {
		return nil, &gqlerror.Error{Message: err.Error()}
	}
	return &post, nil
}

// CreateComment is the resolver for the createComment field.
func (r *mutationResolver) CreateComment(ctx context.Context, input domain.CreateCommentInput) (*domain.Comment, error) {
	comment, err := r.CommentService.CreateComment(input)
	if err != nil {
		return nil, &gqlerror.Error{Message: err.Error()}
	}
	return &comment, nil
}

// Comments is the resolver for the comments field.
func (r *postResolver) Comments(ctx context.Context, obj *domain.Post, page *int, pageSize *int) ([]*domain.Comment, error) {
	comments, err := r.CommentService.GetCommentsByPost(obj.ID, page, pageSize)
	if err != nil {
		return nil, &gqlerror.Error{Message: err.Error()}
	}
	result := make([]*domain.Comment, len(comments))
	for i := range comments {
		c := comments[i]
		result[i] = &c
	}
	return result, nil
}

// Posts is the resolver for the posts field.
func (r *queryResolver) Posts(ctx context.Context, page *int, pageSize *int) ([]*domain.Post, error) {
	posts, err := r.PostService.GetAllPosts(page, pageSize)
	if err != nil {
		return nil, &gqlerror.Error{Message: err.Error()}
	}
	result := make([]*domain.Post, len(posts))
	for i := range posts {
		p := posts[i]
		result[i] = &p
	}
	return result, nil
}

// Post is the resolver for the post field.
func (r *queryResolver) Post(ctx context.Context, id int) (*domain.Post, error) {
	post, err := r.PostService.GetPostByID(id)
	if err != nil {
		return nil, &gqlerror.Error{Message: err.Error()}
	}
	return post, nil
}

// CommentAdded is the resolver for the commentAdded field.
func (r *subscriptionResolver) CommentAdded(ctx context.Context, postID int) (<-chan *domain.Comment, error) {
	panic(fmt.Errorf("not implemented: CommentAdded - commentAdded"))
}

// Comment returns CommentResolver implementation.
func (r *Resolver) Comment() CommentResolver { return &commentResolver{r} }

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Post returns PostResolver implementation.
func (r *Resolver) Post() PostResolver { return &postResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

type commentResolver struct{ *Resolver }
type mutationResolver struct{ *Resolver }
type postResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
