package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"PostService/internal/dataloader"
	"PostService/internal/domain"
	"context"
	"github.com/vektah/gqlparser/v2/gqlerror"
)

func (r *commentResolver) Post(ctx context.Context, obj *domain.Comment) (int, error) {
	return obj.PostID, nil
}

func (r *commentResolver) ReplyTo(ctx context.Context, obj *domain.Comment) (*int, error) {
	return obj.ParentID, nil
}

func (r *commentResolver) Replies(ctx context.Context, obj *domain.Comment) ([]*domain.Comment, error) {
	thunk := dataloader.LoaderFromContext(ctx).Load(ctx, obj.ID)
	result, err := thunk()
	if err != nil {
		return nil, &gqlerror.Error{Message: err.Error()}
	}
	return result, nil
}

func (r *mutationResolver) CreatePost(ctx context.Context, input domain.CreatePostInput) (*domain.Post, error) {
	post, err := r.PostService.CreatePost(input)
	if err != nil {
		return nil, &gqlerror.Error{Message: err.Error()}
	}
	return &post, nil
}

func (r *mutationResolver) CreateComment(ctx context.Context, input domain.CreateCommentInput) (*domain.Comment, error) {
	comment, err := r.CommentService.CreateComment(input)
	if err != nil {
		return nil, &gqlerror.Error{Message: err.Error()}
	}

	r.CommentSubscriptions.Notify(comment.PostID, comment)

	return &comment, nil
}

func (r *postResolver) Comments(ctx context.Context, obj *domain.Post, page *int, pageSize *int) ([]*domain.Comment, error) {
	comments, err := r.CommentService.GetCommentsByPost(obj.ID, page, pageSize)
	if err != nil {
		return nil, &gqlerror.Error{Message: err.Error()}
	}
	result := make([]*domain.Comment, len(comments))
	for i := range comments {
		c := comments[i]
		result[i] = &c
	}
	return result, nil
}

func (r *queryResolver) Posts(ctx context.Context, page *int, pageSize *int) ([]*domain.Post, error) {
	posts, err := r.PostService.GetAllPosts(page, pageSize)
	if err != nil {
		return nil, &gqlerror.Error{Message: err.Error()}
	}
	result := make([]*domain.Post, len(posts))
	for i := range posts {
		p := posts[i]
		result[i] = &p
	}
	return result, nil
}

func (r *queryResolver) Post(ctx context.Context, id int) (*domain.Post, error) {
	post, err := r.PostService.GetPostByID(id)
	if err != nil {
		return nil, &gqlerror.Error{Message: err.Error()}
	}
	return post, nil
}

func (r *subscriptionResolver) CommentAdded(ctx context.Context, postID int) (<-chan *domain.Comment, error) {
	id, ch, err := r.CommentSubscriptions.CreateSubscription(postID)
	if err != nil {
		return nil, &gqlerror.Error{Message: err.Error()}
	}

	// пользователь отключился - удаляем подписку
	go func() {
		<-ctx.Done()
		_ = r.CommentSubscriptions.DeleteSubscription(postID, id)
	}()

	return ch, nil
}

func (r *Resolver) Comment() CommentResolver { return &commentResolver{r} }

func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

func (r *Resolver) Post() PostResolver { return &postResolver{r} }

func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

type commentResolver struct{ *Resolver }
type mutationResolver struct{ *Resolver }
type postResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
