// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package domain

type CreateCommentInput struct {
	Author  string `json:"author"`
	Content string `json:"content"`
	Post    int    `json:"post"`
	ReplyTo *int   `json:"replyTo,omitempty"`
}

type CreatePostInput struct {
	Author          string  `json:"author"`
	Title           *string `json:"title,omitempty"`
	Content         string  `json:"content"`
	CommentsAllowed bool    `json:"commentsAllowed"`
}

type Mutation struct {
}

type Query struct {
}

type Subscription struct {
}
